### ISSUE TITLE
are you interested in freelancing?

### ISSUE THREAD

**Issue by deepseek** [acbull/GPT-GNN#1]
@acbull

**Comment by acbull** [comment]
Sorry, what do you mean by "freelancing"?

**Comment by deepseek** [comment]
i have a task that i want to solve using graph neural networks.
dealing predicting the reading-order
are you interested?

**Comment by acbull** [comment]
If you want to use my previous work to solve it, I'm glad to discuss the details, but I cannot directly work on them.
