### ISSUE TITLE
About the format of the data set?

### ISSUE THREAD

**Issue by yangxia605** [acbull/GPT-GNN#14]
hi @acbull 
my case is that i should use a  sample of the training data sets to  build a graph but not all of the training data sets.
that is to say: Use the internal elements of the sample to construct a heterogeneous graph.
I was wonder if i can use GPT-GNN to fine-tuning it and then Do a classification task in the downstream ?

thanks!!!

**Comment by acbull** [comment]
Sure, pre-training is very suitable for your case.

About data format, you can refer to https://github.com/acbull/GPT-GNN/blob/2409049c9f9df780cd4e4c6403a0b79980776afc/GPT_GNN/data.py#L20 to check our data structure. Or you can use your own data structure, and adapt our code to your setting.

To construct such a graph, you can refer to prepreocess_*.py as a reference.

**Comment by yangxia605** [comment]
thank you!!!
