### ISSUE TITLE
f1_score

### ISSUE THREAD

**Issue by Mobzhang** [acbull/GPT-GNN#16]
Hi acbull,
When I use finetune_reddit.py, i get an error name 'f1_score' is not defined int 203 line.
and I didnt find f1_score reference  in example_reddit actually. so  could you tell me about the f1_score's detail? 
thanks!

**Comment by acbull** [comment]
It's https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html

Sorry for the mistake. I've added that in the file.
