### ISSUE TITLE
没有找到 preprocess_OAG.py

### ISSUE THREAD

**Issue by ghkk** [acbull/GPT-GNN#2]
麻烦提供一下，谢谢！

**Comment by ghkk** [comment]
找到了，多谢！

**Comment by xiaolan98** [comment]
where is the preprocess_OAG.py?

**Comment by ghkk** [comment]
@xiaolan98 https://github.com/acbull/pyHGT/blob/master/OAG/preprocess_OAG.py

**Comment by xiaolan98** [comment]
Thanks.
