### ISSUE TITLE
About ablation studies on base GNNs

### ISSUE THREAD

**Issue by Kqiii** [acbull/GPT-GNN#25]
Hi, 

Thank you for your good paper!

The caption of Tab.2 says that experiments included here are under the _combined transfer setting_, where the accuracy for GPT-GNN + HGT is 0.407:

![image](https://user-images.githubusercontent.com/38380341/101882819-58dcc880-3bd1-11eb-8437-0979f55e1115.png)

However, according to Tab.1, GPT-GNN + HGT under this setting achieves acc of 0.393. Rather, 0.407 is the result of GPT-GNN+ HGT under the _field transfer setting_. 

Could you please clarify the setting used in Tab.2?

Additionally, I am also wondering how you evaluated GAE, GraphSage (unsp.), and Graph Infomax in experiments in Tab.1. As far as I know, GNN encoders used in the above three papers are GCN, the GraphSage architecture, and GIN, which are designed to learn from homogeneous graphs. May I ask whether you also used these GNN encoders, i.e., GCN, GraphSage and GIN, for related experiments in Tab.1? If so, could you please elaborate on how to apply these encoders to OAG and Amazon that are heterogeneous graphs?

Thank you!

**Comment by acbull** [comment]
In table 1, GPT-GNN on whole OAG under field transfer setting is .407±.107. (https://arxiv.org/pdf/2006.15437.pdf). 0.393 is for time + field transfer.

We treat GAE, GraphSage (unsp.), and Graph Infomax as pre-training paradigm, so they only provide unsupervised guidance to train the GNN model. The default GNN model is HGT. 

To evaluate the different encoders, we have this Table 2. To handle large-scale graphs, we use the same sampling procedure as described (and implemented) similar to HGT. For GCN and GAT, we simply treat the sampled graph as homogeneous graph, while maintaining the first layer (feature adaptation) for a different types of nodes.

**Comment by Kqiii** [comment]
Thank you for your response!
