### ISSUE TITLE
How to create the node permutation?

### ISSUE THREAD

**Issue by voladorlu** [acbull/GPT-GNN#26]
Hi, @acbull. thank you so much for sharing the code. I have a question on the graph preprocessing. May I ask how to determinate the order (permutation) of nodes in a sampled subgraph? What's the criterion that we refer to? -:)

**Comment by acbull** [comment]
It's a good question that I haven't do a thorough analysis yet.

Currently, I just use my own sampling method to determine the node order, by firstly randomly picking a batch of nodes, and layer-wise expand the neighborhood set. You can refer to data.py for more details.

Ideally, if we know the exact node sequence (such as temporal sequence) to generate the node, it would be better.

**Comment by voladorlu** [comment]
I see. Thank you so much for a quick response.
