### ISSUE TITLE
Results of example data

### ISSUE THREAD

**Issue by bangann** [acbull/GPT-GNN#7]
Hi, could you please provide the result of GPT-GNN on the OAG-CS data? I'm wondering what is the expected result if I run your code directly on the example data you provided. It would be great if a result for baseline (no pre-train) could also be provided. Thank you!

**Comment by acbull** [comment]
The result is given in the paper (the time-transfer setting for OAG, including no pre-training and with GPT-GNN pretrain).

**Comment by bangann** [comment]
Thank you! I missed it.
