### ISSUE TITLE
Error when using han or hetgnn

### ISSUE THREAD

**Issue by bangann** [acbull/GPT-GNN#8]
Hi, when I finetune directly (without pre-train) on models based on han or hetgnn, I encounter with this error:

Start Loading Graph Data...
Finish Loading Graph Data!
Data Preparation: 91.0s
Traceback (most recent call last):
  File "finetune_OAG_PF.py", line 252, in <module>
    res  = classifier.forward(node_rep[x_ids])
TypeError: 'NoneType' object is not subscriptable

Do you have any ideas for the reasons? Thank you!

**Comment by acbull** [comment]
How do you train on han and hetgnn?

**Comment by bangann** [comment]
just set --conv_name to be han

**Comment by acbull** [comment]
I didn't provide the real implementation of han and hetgnn in this repo. I would consider adding them later on. I would suggest you directly test on our HGT model.

Thanks,
Ziniu
