### ISSUE TITLE
can't install environment successfully use requirement.txt

### ISSUE THREAD

**Issue by herbertguoqi** [acbull/GPT-GNN#9]
such as cant install torch-sparse...

**Comment by acbull** [comment]
For installing pytorch_geometric and its related packages (e.g., torch-sparse), please refer to: https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#

**Comment by acbull** [comment]
Or, you can directly copy the docker environment provided in: https://github.com/acbull/pyHGT/tree/master/Docker

**Comment by herbertguoqi** [comment]
> Or, you can directly copy the docker environment provided in: https://github.com/acbull/pyHGT/tree/master/Docker

wonderful! i will try

**Comment by herbertguoqi** [comment]
thx！
